import { describe, expect, it, vi } from "vitest";
import { runSchedulerTick, type SchedulerDefinition, type SchedulerStore } from "../../../src/ops/scheduler-tick.js";
function store(definitions: SchedulerDefinition[]): SchedulerStore { return { now: vi.fn(async () => new Date("2026-07-21T10:07:00.000Z")), definitions: vi.fn(async () => definitions), enqueue: vi.fn(async (input) => ({ id: `cmd-${input.jobName}`, ...input })) } as unknown as SchedulerStore; }
describe("runSchedulerTick", () => {
 it("creates only due enabled commands in their UTC time slice and dispatches them", async () => { const s=store([{name:"collect_github_trending",executor:"github",capability:"github.trending",workflow:"trending.yml",enabled:true,schedule:{minute:7,hour:"*"},parameters:{}},{name:"retention",executor:"github",capability:"maintenance.retention",workflow:"retention.yml",enabled:true,schedule:{minute:45,hour:"*"},parameters:{}},{name:"evaluate_success",executor:"github",capability:"maintenance.evaluate",workflow:"evaluate-success.yml",enabled:false,schedule:{minute:7,hour:"*"},parameters:{}}]); const dispatch=vi.fn(async()=>undefined); const result=await runSchedulerTick({store:s,dispatch}); expect(result).toMatchObject({created:1,dispatched:1,observed:false}); expect(s.enqueue).toHaveBeenCalledWith(expect.objectContaining({jobName:"collect_github_trending",scheduledFor:new Date("2026-07-21T10:07:00.000Z")})); expect(dispatch).toHaveBeenCalledWith(expect.objectContaining({id:"cmd-collect_github_trending",workflow:"trending.yml"})); });
 it("supports observe mode without creating or dispatching commands", async () => { const s=store([{name:"retention",executor:"github",capability:"maintenance.retention",workflow:"retention.yml",enabled:true,schedule:{minute:7,hour:"*"},parameters:{}}]); const dispatch=vi.fn(); const result=await runSchedulerTick({store:s,dispatch,observe:true}); expect(result).toMatchObject({created:1,dispatched:0,observed:true}); expect(s.enqueue).not.toHaveBeenCalled(); expect(dispatch).not.toHaveBeenCalled(); });
 it("does not duplicate a command and records dispatch failures", async () => { const s=store([{name:"retention",executor:"github",capability:"maintenance.retention",workflow:"retention.yml",enabled:true,schedule:{minute:7,hour:"*"},parameters:{}}]); (s.enqueue as ReturnType<typeof vi.fn>).mockRejectedValueOnce(Object.assign(new Error("duplicate"),{code:"duplicate_command"})); const result=await runSchedulerTick({store:s,dispatch:vi.fn()}); expect(result).toMatchObject({created:0,dispatched:0,errors:[{jobName:"retention",code:"duplicate_command"}]}); });
 it("skips paused jobs and keeps a dispatch failure observable", async () => { const s=store([{name:"retention",executor:"github",capability:"maintenance.retention",workflow:"retention.yml",enabled:true,pausedAt:new Date("2026-07-21T10:00:00.000Z"),schedule:{minute:7,hour:"*"},parameters:{}},{name:"generate_report",executor:"github",capability:"reports.daily",workflow:"daily-report.yml",enabled:true,schedule:{minute:7,hour:"*"},parameters:{}}]); const dispatch=vi.fn(async()=>{ throw Object.assign(new Error("down"),{code:"github_dispatch_failed"}); }); const result=await runSchedulerTick({store:s,dispatch}); expect(result).toMatchObject({created:1,dispatched:0,errors:[{jobName:"generate_report",code:"github_dispatch_failed"}]}); expect(s.enqueue).toHaveBeenCalledTimes(1); });
});
